### ISSUE TITLE
Cannot run Keybender on Windows

### ISSUE THREAD

**Issue by maturabg** [ShinyCode/keybender#1]
Hello,
I was wondering if I can get some help with getting Keybender up and running on my system. I downloaded and extracted v1.0.0 locally but everytime I run the exe I get error "Failed to execute script keybender".

**Comment by ShinyCode** [comment]
Thanks for opening this issue up. I got the same error running it - I'm running this on a different system from the original on which I compiled it, and it may be due to the required dependencies not existing (and the executable not really being self-contained). I can take a look (and possibly recompile Keybender if needed) when I have the chance.

If I may know, what aspects of Keybender are you interested in? If it's just for using the computer keyboard as a MIDI controller (and not for sequencing), I could potentially upload a lite version of Keybender (without a GUI) to be run from the command line.

**Comment by maturabg** [comment]
Thanks for replying. Yeah, I intend to use it just as MIDI controller.

**Comment by ShinyCode** [comment]
Okay. Found the time to put Keybender Lite up [here](https://github.com/ShinyCode/keybender-lite)! Try this out. Feel free to open up an issue on that repo if installation doesn't work (I did do some testing though, so I don't expect you to run into too many problems).

Enjoy!
